# Generated by Django 4.2.7 on 2024-03-22 19:45

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partei_name', models.CharField(help_text='<i>Maximal 50 Zeichen</i><br>\n    Gib den Namen der Partei an, der für den Benutzer angezeigt werden soll.', max_length=50, verbose_name='Name')),
                ('partei_beschreibung', models.TextField(blank=True, help_text='<i>Maximal 1000 Zeichen</i><br>\n    Beschreibung für die Partei, wird auf der Ergebnis-Seite angezeigt.', max_length=1000, verbose_name='Beschreibung')),
                ('partei_bild', models.ImageField(blank=True, default=None, help_text='Logo oder Foto, das auf der Ergebnis-Seite angezeigt werden soll.', null=True, upload_to='partei_bild', verbose_name='Bild')),
                ('partei_farbe', colorfield.fields.ColorField(blank=True, default=None, help_text='Akzentfarbe der Partei, die als Streifen neben dem Ergebnis angezeigt wird.', image_field=None, max_length=25, null=True, samples=None, verbose_name='Akzentfarbe')),
            ],
            options={
                'verbose_name': 'Partei',
                'verbose_name_plural': 'Parteien',
            },
        ),
        migrations.CreateModel(
            name='These',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('these_keyword', models.CharField(help_text='<i>Maximal 40 Zeichen</i><br>\n    Ein kurzes Schlagwort, um die These zu beschreiben. Wird in der\n    Seitenleiste des Wahlrechners angezeigt.<br>\n    <b>Beispiel:</b> Klimanotstand', max_length=40, verbose_name='Schlagwort')),
                ('these_text', models.TextField(help_text='<i>Maximal 400 Zeichen</i><br>\n    Der vollständige Text der These.<br>\n    <b>Beispiel:</b> Die Stadt XYZ sollte den Klimanotstand ausrufen.', max_length=400, verbose_name='Vollständige These')),
                ('these_nr', models.FloatField(help_text='Die Thesen-Nummer gibt Auskunft über die Reihenfolge, in der alle Thesen\n    angezeigt werden. Dabei wird als erstes die These mit der niedrigsten Thesen-Nummer angezeigt,\n    danach die These mit der jeweils nächst größeren Thesen-Nummer, usw. Die Thesen-Nummer lässt\n    sich also als Priorität für die angezeigte Reihenfolge verstehen, und kann auch eine krumme\n    Zahl sein.<br>\n    <b>Beispiel:</b> Die These, die zuerst angezeigt werden soll, hat die Nummer 1. Die zweite These\n    die Nummer 2, usw.', unique=True, verbose_name='Thesen-Nummer')),
            ],
            options={
                'verbose_name': 'These',
                'verbose_name_plural': 'Thesen',
            },
        ),
        migrations.CreateModel(
            name='Antwort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antwort_position', models.CharField(choices=[('a', 'stimmt zu'), ('b', 'stimmt teilweise zu'),('d', 'stimmt nicht zu'),('e', 'stimmt teilweise nicht zu'), ('n', 'neutral')], help_text='Wähle aus, wie sich die Partei zu der ausgewählten These positioniert.', max_length=1, verbose_name='Position zur These')),
                ('antwort_text', models.TextField(blank=True, help_text='<i>Maximal 1000 Zeichen</i><br>\n    Vollständige Antwort/Begründung der Partei zu ihrer Position.', max_length=1000, verbose_name='Antwort')),
                ('antwort_partei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wahlrechner.partei', verbose_name='Partei')),
                ('antwort_these', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wahlrechner.these', verbose_name='These')),
            ],
            options={
                'verbose_name': 'Antwort',
                'verbose_name_plural': 'Antworten',
            },
        ),
    ]
