# Generated by Django 4.2.7 on 2024-03-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wahlrechner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antwort',
            name='antwort_position',
            field=models.CharField(choices=[('a', 'stimmt zu'), ('b', 'stimmt teilweise zu'), ('d', 'stimmt nicht zu'), ('e', 'stimmt teilweise nicht zu'), ('n', 'neutral')], help_text='Wähle aus, wie sich die Partei zu der ausgewählten These positioniert.', max_length=1, verbose_name='Position zur These'),
        ),
    ]
